In [6]:
import pandas as pd
import datetime

In [87]:
holidays_df = pd.read_csv('holidays_events.csv')
oil_df = pd.read_csv('oil.csv')
stores_df = pd.read_csv('stores.csv')
test_df = pd.read_csv('test.csv')
train_df = pd.read_csv('train.csv')
transactions_df = pd.read_csv('transactions.csv')

In [88]:
joined_df = train_df.merge(holidays_df, on='date', how='left')
joined_df = joined_df.merge(oil_df, on='date', how='left')
joined_df = joined_df.merge(stores_df, on = 'store_nbr', how='left')
# joined_df = joined_df.merge(transactions_df, on='store_nbr', how='left')
joined_df = joined_df.set_index('id')

In [89]:
class DateFormater():
    @staticmethod
    def day(d):
        year, month, day = [int(x) for x in d.split('-')]
        date = datetime.datetime(year, month, day)
        return date.strftime('%a') 

    @staticmethod
    def month(d):
        year, month, day = [int(x) for x in d.split('-')]
        date = datetime.datetime(year, month, day)
        return date.strftime('%B')

In [90]:
joined_df['day_of_week'] = joined_df['date'].map(lambda d: DateFormater.day(d))
joined_df['month'] = joined_df['date'].map(lambda d: DateFormater.month(d))

In [91]:
joined_df['dcoilwtico'] = joined_df['dcoilwtico'].interpolate(method='linear')

In [ ]:
joined_df['dcoilwtico'].loc[0:1782] = joined_df.loc[joined_df.dcoilwtico.first_valid_index()]['dcoilwtico']

C:\Users\admin55\AppData\Local\Temp\ipykernel_9892\3054555463.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  joined_df['dcoilwtico'].loc[0:1782] = 93.14

In [ ]:
y = joined_df['sales']
X = joined_df.drop(columns=['sales', 'date', 'description'])

In [111]:
X.head()

,date,store_nbr,family,onpromotion,type_x,locale,locale_name,description,transferred,dcoilwtico,city,state,type_y,cluster,day_of_week,month
id,,,,,,,,,,,,,,,,
0,2013-01-01,1,AUTOMOTIVE,0,Holiday,National,Ecuador,Primer dia del ano,False,93.14,Quito,Pichincha,D,13,Tue,January
1,2013-01-01,1,BABY CARE,0,Holiday,National,Ecuador,Primer dia del ano,False,93.14,Quito,Pichincha,D,13,Tue,January
2,2013-01-01,1,BEAUTY,0,Holiday,National,Ecuador,Primer dia del ano,False,93.14,Quito,Pichincha,D,13,Tue,January
3,2013-01-01,1,BEVERAGES,0,Holiday,National,Ecuador,Primer dia del ano,False,93.14,Quito,Pichincha,D,13,Tue,January
4,2013-01-01,1,BOOKS,0,Holiday,National,Ecuador,Primer dia del ano,False,93.14,Quito,Pichincha,D,13,Tue,January